theme: osuny
_merge: deep
params:
  plausible: campus-transition.org
  summary:
    position: hero
  search:
    active: true
  logo:
    header: '/assets/images/logo.svg'
    footer: '/assets/images/logo.svg'
  persons:
    index:
      layout: list
  posts:
    index:
      layout: grid
  programs:
    index:
      options:
        summary: true
    single:
      options:
        diploma_certification: false
        logo: false
  projects:
    index:
      options:
        categories: false
        summary: false
  home:
    head:
      title: site
  seo:
    title:
      separator: "•"