theme: osuny
_merge: deep
params:
  summary:
    position: hero
  search:
    active: true
  logo:
    header: '/assets/images/logo.svg'
    footer: '/assets/images/logo.svg'
  menu:
    primary:
      level_2:
        title:
          active: true
  persons:
    index:
      layout: list
  posts:
    index:
      layout: grid
  programs:
    index:
      options:
        summary: true
      taxonomies: true
    single:
      options:
        diploma_certification: false
        logo: false
